export { default as Dashboard } from "./AdminPage/Dashboard/Dashboard";
export { default as Login } from "./Login/login";
export { default as Landing } from "./LandingPage/Landing";
export { default as Register } from "./Register/register";
export { default as Question } from "./Question/question";
export { default as Language } from "./Language/language";
export { default as HomePage } from "./HomePage/HomePage";
export { default as Level } from "./Level/Level";
export { default as CreateQuestion } from "./CreateQuestion/createQuestion";
